CREATE SEQUENCE seq_rutas START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_vehiculos START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_conductores START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_pasajeros START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_viajes START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_boletos START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_pagos START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_auditoria_viajes START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE seq_log_errores START WITH 1 INCREMENT BY 1;

